### ISSUE TITLE
Instructions for running from source don't work.

### ISSUE THREAD

**Issue by dflock** [willthames/ansible-review#20]
The instructions in the README for running from source are:

```
# Install dependency https://github.com/willthames/ansible-lint
git clone https://github.com/willthames/ansible-review
export PYTHONPATH=$PYTHONPATH:`pwd`/ansible-review/lib
export PATH=$PATH:`pwd`/ansible-review/bin
```

There's no `/ansible-review/bin` sub-folder, so these instructions don't work?

**Comment by willthames** [comment]
Found a way to reintroduce the script while retaining python setuptools entry points
