### ISSUE TITLE
Provide default standards

### ISSUE THREAD

**Issue by elleryq** [willthames/ansible-review#3]
Could you provide default standards?

**Comment by willthames** [comment]
Hi @elleryq, it's not that I can't, it's more that every organisation will have it's own standards, and they will evolve over time. 

However, I can probably share a large proportion of the standards we use as an example, if that would be helpful.

I'll keep this open until I've done that.

**Comment by willthames** [comment]
They won't be default standards though, just an example for a starting point (but you would be able to point your configuration at them)

**Comment by elleryq** [comment]
Thank you~ :)
