### ISSUE TITLE
How do you get ansible-review to exit non-zero?

### ISSUE THREAD

**Issue by ryancurrah** [willthames/ansible-review#32]
If a review fails. It exits with a return code 0. We want it to return non-zero to stop Jenkins from continuing with the build. Is it possible?

**Comment by ryancurrah** [comment]
In order for a standard to cause a non-zero exit you need assign a version to your standard.

**Comment by willthames** [comment]
Sorry I didn't see this the first time around, I was on holiday. This is a good reminder to check the other outstanding issues though

**Comment by ryancurrah** [comment]
It's all good no need to apologize you're doing gods work by making everyone else's lives easier. 

I thought instead of leaving it open (annoying for you) or closing it without an explanation (annoying for everyone) that I would leave the answer I found here for others to benefit as well. 

If you have a Patreon or something let me know. I'd like to buy you a beer or two.
