### ISSUE TITLE
Warnings triggered for jinja2 variables even if code is commented

### ISSUE THREAD

**Issue by nvtkaszpir** [willthames/ansible-review#35]
Looks like ansible-review or ansible-lint is triggering warning if var is detected among jinja2 curly braces but actual code is commented out.
This happens in .yml file, not in the template.

**Example:**

```yaml
---
# if below variable is empty then ansible will try to download "{{some_var}}.md5"
i_like_turtles: true
```

**Output:**
```text
WARN: Best practice "Variable uses should contain whitespace" not met:
.../defaults/main.yml:35: [EXTRA0001] Variables should have spaces after {{ and before }}
```
**Expected output:**
Should not generate WARN at all, because code is commented out.

**Comment by willthames** [comment]
It's fine, you can put spaces in the comments too :)

**Comment by nvtkaszpir** [comment]
You say vars within comments should be also surrounded by spaces?
Well, in theory it is a part of code, which is not executed.
On the other hand if we use comments then we should conform to coding standard everywhere.

After second thought, indeed, the check should run everywhere and nit-pick anything committed :)
