### ISSUE TITLE
Classify LICENCE and exclude dotfiles

### ISSUE THREAD

**Issue by xoxys** [willthames/ansible-review#50]
For now, LICENCE Files are not classified by ansible-review. Also dotfiles (in my case .drone.yml) would be handled as a playbook so i think it would be a better solution to exclude (optionally) dotfiles from review. DO you accept pull requests?

By the way, whats the status of the project? There are Pull Requests not merged since April 2017..

**Comment by willthames** [comment]
Don't forget to look at the closed PRs as well as the open PRs - that gives a better indication of status.

dotfiles make sense as a default ignore. 

I'm not sure I want to exclude LICENSE by default (where do you stop - CHANGELOG, README, etc., with or without .txt or .md suffixes) - might be better to just add them to an exclusions list in the configuration
