### ISSUE TITLE
Quiet mode prints warnings

### ISSUE THREAD

**Issue by AMeng** [willthames/ansible-review#6]
When using the `-q` flag, warning messages are still printed. Is this the intended behavior? I would expect that only errors are shown. I'm glad to open a PR to address this but wanted to get feedback first.

**Comment by willthames** [comment]
It's expected. I don't really want to hide the warnings. 

But might be open to a fix that adds `-v` for INFO - so quiet only prints errors, normal mode is print warnings, and verbose prints info.
