### ISSUE TITLE
Classification of files as group_vars not working correctly

### ISSUE THREAD

**Issue by xoxys** [willthames/ansible-review#60]
There seems to be a bug in classification of files under group_vars if group_vars contains subdirectories e. g.

group_vars
|___ group_1
|_______ main.yml
|_______ vaulted.yml
|___ group_2
...

Regards

**Comment by willthames** [comment]
@apatard, do you want to convert your commit to a PR?

If not, do you mind if I just cherry-pick your commit?

**Comment by apatard** [comment]
@willthames I've submitted a PR, I guess it should be easier for you.

**Comment by rrey** [comment]
Hi there,

It seems that this issue could easily be closed as the fix is available, am I wrong ?
