### ISSUE TITLE
Broken PyPI metadata and related problems

### ISSUE THREAD

**Issue by webknjaz** [willthames/ansible-review#70]
Look at https://pypi.org/project/ansible-review/#description, it shows:
```text
Project description
The author of this package has not provided a project description
```

This probably means that you use outdated setuptools when building the dist.

There's also a few other problems I see:
1) `setup.cfg` refers to `README.md`, but RST is default for warehouse. To make it understand makrdown you need to provide extra setting with mime type specified correctly (and use up-to-date setuptools)
2) PyPI page would also benefit from `project_urls` metadata option
3) It's better readable when you keep metadata in declarative config. Here's example shim for making old setuptools understanding how to read that: https://github.com/cherrypy/cheroot/blob/master/setup.py
4) You publish only `sdist`, while per current recommendations you should *also* publish a universal wheel as well. This would also save end-users from having to have modern setuptools in place.
5) Version is hardcoded, alternatively it could be stored in a Git tag. There's a plugin called `setuptools-scm`, which helps to handle this smoothly.
6) Manual building/publishing is error-prone (because of human factor). I suggest changing this towards using CI/CD (the project is about automation, but doesn't have automation in place? hmm..)

So if you're open to such changes let me know as I've gotten a very good experience with all I mentioned above and I can send a PR or/and consult you on those if you have any questions/conserns.

**Comment by webknjaz** [comment]
Hm.. it's curious that some old versions (https://pypi.org/project/ansible-review/0.9.0/#description) have wheels and description published (misrendered markdown though)

**Comment by gundalow** [comment]
We (Ansible) can fix this in `ansible-lint` then raise a PR to update it here in `ansible-review` as well

**Comment by webknjaz** [comment]
Yep, working on submitting a similar issue to `ansible-lint` now.
