### ISSUE TITLE
Embrace parseable output to stdout

### ISSUE THREAD

**Issue by webknjaz** [willthames/ansible-review#74]
It is common to print smth parseable for the sake of pipe chaining among POSIX utils.
However, ansible-review doesn't seem to care about this:
```console
✦ ➜ ansible-review rebuild-world.yml -q 1>/dev/null
Couldn't parse task at rebuild-world.yml:8 (no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '<unicode string>': line 8, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

(could not open file to display line))
{ 'eix': {'__file__': 'rebuild-world.yml', '__line__': 9, 'action': 'sync'},
  'name': 'Sync portage/layman trees and index ebuilds'}
```

I'm building a GitHub App integration demo, which would really benefit from not having to use heuristics and manual conditional parsing to retrieve structured result data.

**Comment by webknjaz** [comment]
@willthames ?

**Comment by webknjaz** [comment]
FWIW here's my playground: https://github.com/webknjaz/ansible-gentoo-laptop/pull/4/checks?check_run_id=35656446
And the source code: https://github.com/webknjaz/ansiwatch-bot

**Comment by willthames** [comment]
If there is a PR that would fix this, let me know. I've had a rereview of #28 but that needs a rebase and I'm still not convinced by the custom option parser.

**Comment by webknjaz** [comment]
Yeah, I'm also not sure whether that solution is a good fit.
OTOH I'd probably prefer just one switch to emit everything as JSON or similar, maybe JSONL.

The problem is that I don't know whether it needs architectural changes to unify output format as well.
And I also think that for my purposes using Python API would be even better which would probably require a slight change like putting some chunk of logic from `main()` into its separate function.
