### ISSUE TITLE
Broken EXTRA0008 check

### ISSUE THREAD

**Issue by webknjaz** [willthames/ansible-review#76]
It errors out if there's `tasks:` in playbook, but using `roles:` is currently discouraged. One should use `tasks:` + `import_role:` instead. This check should be improved.

**Comment by willthames** [comment]
> using roles: is currently discouraged. 

[citation needed]

Using roles seems far better than using import_role.

**Comment by webknjaz** [comment]
Okay, so I've raised a discussion in our internal (Ansible Core) slack.
Takeaways:
- roles are supported
  "using `roles:` doesn't mean you can't also use tasks. it's `pre_tasks` and `post_tasks`" (@jctanner)
- import_role is another more flexible way to use instead of roles if it fits one's requirements
  "Use of `roles:` should not be discouraged.

  It’s equivalent to `import_role`.
  Use either when they make sense.
  Using `import_role` makes it more obvious in which order things get executed rather than having to use the other directives to control execution order." (@samdoran)
- folks agree that ansible-review is wrong in this case and it's very case-dependent
  "[...] _Especially_ in this case, when the use of `roles` vs `import_role` is very situationally dependent." (@samdoran)
- "in most cases `roles:` should be  avoided (when roles have tasks to execute, as import/include_role give much better control, but if you have a role that provides plugins or vars for example, those make a lot of sense in 'roles:'" (@bcoca)

**Comment by willthames** [comment]
I missed your response, apologies

I agree with your reasoning. I might just delete the rule - it's out of date with how ansible works since import_role/include_role exist.
