### ISSUE TITLE
Warnings vs Errors

### ISSUE THREAD

**Issue by ansiblejunky** [willthames/ansible-review#80]
Is there a way to define rules as just `warnings` instead of an `error`? Meaning, the rule will be listed when running `ansible-review` but it won't produce a return code of 1, which prevents the git commit. I see this feature on `yamllint` tool and would love to be able to do that here too. Thanks!

**Comment by willthames** [comment]
Yes, that's a standard feature.

From the README.md (it could probably be clearer):

> To add standards that are advisory, don't set the version. These will cause a message to be displayed but won't constitute a failure.

Hopefully that helps, let me know if you need any more info

**Comment by ansiblejunky** [comment]
Yes, I think it definitely needs to be made more clear on the docs. tbh, I am still not fully understanding. So there are 2 versions - the standards version and the version that is inside each rule defined in the standards file? if the standards version is greater than the rule version then it becomes a warning? Perhaps you can give some better example and explanation?

**Comment by willthames** [comment]
I talk a bit about versioned standards at https://willthames.github.io/2016/06/28/announcing-ansible-review.html

This means that you can update your standards without roles developed against earlier standards failing.

**Comment by ansiblejunky** [comment]
Thanks @willthames, I think I understand now. We generally don't set the Standards in our playbooks because we always want to apply the latest version of the lint rules. So in our `standards.py` we set the latest version to `1.0` here:

```
# Update this every time standards version increase
latest_version = Standard(dict(
    check=noop,
    name="No-op check to ensure latest standards version is set",
    version="1.0",
    types=[]
))
```

And then, the rules we want to FAIL in our `standards.py` we make sure they have `version` set as we do here:
```
tasks_are_named = Standard(dict(
    name="Tasks and handlers must be named",
    check=lintcheck('ANSIBLE0011'),
    version="0.0",
    types=["playbook", "task", "handler"],
))
```
Then when the playbook or task file breaks that rule, a FAIL will occur for that specific rule. If we want the rule to only be "suggestive" and warn developers, we remove the `version` from the above rule.
