### ISSUE TITLE
meta tasks not known by review script

### ISSUE THREAD

**Issue by mkeir** [willthames/ansible-review#9]
In running a review, the following error is reported which is not correct.

ERROR: Standard "Tasks and handlers must be named" not met:
database/tasks/postgresql.yml:61: [ANSIBLE0011] All tasks should be named

The line concerned is:
- meta: flush_handlers

There may need to be special handling enabled to know this task type.

**Comment by willthames** [comment]
This is already tracked at willthames/ansible-lint#176

I'll consider this a +1 to fix that bug :)
